merge into [Framework].[PaneType] as Target
using ( values
     ('7e60acaa-e3f8-4555-913c-b583b07c3af7', 'Catalog | Book - Edit',                          null,                                                                                         'Crudspa.Samples.Catalog.Client.Plugins.PaneType.BookEdit, Crudspa.Samples.Catalog.Client')
    ,('cf04391f-4e91-4fd3-a35f-c3747b1572df', 'Catalog | Book - Find',                          null,                                                                                         'Crudspa.Samples.Catalog.Client.Plugins.PaneType.BookFind, Crudspa.Samples.Catalog.Client')
    ,('f40ea215-88ed-4df0-8c17-34b5178035e3', 'Catalog | Catalog - Edit',                       null,                                                                                         'Crudspa.Samples.Catalog.Client.Plugins.PaneType.CatalogEdit, Crudspa.Samples.Catalog.Client')
    ,('4d4af830-edce-4df4-92ee-fc303d42472e', 'Catalog | Catalog Contact - Edit',               null,                                                                                         'Crudspa.Samples.Catalog.Client.Plugins.PaneType.CatalogContactEdit, Crudspa.Samples.Catalog.Client')
    ,('b7030cac-ca49-442a-86f1-cc3a87ac6900', 'Catalog | Catalog Contact - Find',               null,                                                                                         'Crudspa.Samples.Catalog.Client.Plugins.PaneType.CatalogContactFind, Crudspa.Samples.Catalog.Client')
    ,('0ae15328-96be-4b07-bee8-a21f99903bdb', 'Catalog | Movie - Edit',                         null,                                                                                         'Crudspa.Samples.Catalog.Client.Plugins.PaneType.MovieEdit, Crudspa.Samples.Catalog.Client')
    ,('9adc25a9-1c58-4bfc-826a-0a632f23c605', 'Catalog | Movie - Find',                         null,                                                                                         'Crudspa.Samples.Catalog.Client.Plugins.PaneType.MovieFind, Crudspa.Samples.Catalog.Client')
    ,('607c498d-8ead-4126-8463-288bdc13b6bf', 'Catalog | Movie Credit - Edit',                  null,                                                                                         'Crudspa.Samples.Catalog.Client.Plugins.PaneType.MovieCreditEdit, Crudspa.Samples.Catalog.Client')
    ,('6a36256b-c0e2-4f65-ab2d-0a0a854ba057', 'Catalog | Movie Credit - List for Movie',        null,                                                                                         'Crudspa.Samples.Catalog.Client.Plugins.PaneType.MovieCreditListForMovie, Crudspa.Samples.Catalog.Client')
    ,('a1a750e6-07b0-4bfe-8bfc-8b9ce3dc8bc8', 'Catalog | Shirt - Edit',                         null,                                                                                         'Crudspa.Samples.Catalog.Client.Plugins.PaneType.ShirtEdit, Crudspa.Samples.Catalog.Client')
    ,('f3fcdc97-3dcb-4909-ae5c-48afb579e2cf', 'Catalog | Shirt - Find',                         null,                                                                                         'Crudspa.Samples.Catalog.Client.Plugins.PaneType.ShirtFind, Crudspa.Samples.Catalog.Client')
    ,('3a172e8d-d547-4924-9b62-51c511ddba76', 'Catalog | Shirt Option - Many for Shirt',        null,                                                                                         'Crudspa.Samples.Catalog.Client.Plugins.PaneType.ShirtOptionManyForShirt, Crudspa.Samples.Catalog.Client')
    ,('3288e5df-7957-44d8-8b0d-a482490b2456', 'Composer | Composer - Edit',                     null,                                                                                         'Crudspa.Samples.Composer.Client.Plugins.PaneType.ComposerEdit, Crudspa.Samples.Composer.Client')
    ,('42b4a2e8-96e6-4d98-94e2-02be7ae1bc5d', 'Composer | Composer Contact - Edit',             null,                                                                                         'Crudspa.Samples.Composer.Client.Plugins.PaneType.ComposerContactEdit, Crudspa.Samples.Composer.Client')
    ,('f6d92688-f316-47b0-a4df-e1ca2a88553a', 'Composer | Composer Contact - Find',             null,                                                                                         'Crudspa.Samples.Composer.Client.Plugins.PaneType.ComposerContactFind, Crudspa.Samples.Composer.Client')
    ,('706215be-da1b-42b4-9457-63d77ef0607f', 'Content | Achievement - Many for Portal',        null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.AchievementManyForPortal, Crudspa.Content.Design.Client')
    ,('bebdcb61-c627-456a-baf0-8de9d389337f', 'Content | Binder - Display',                     'Crudspa.Content.Design.Client.Plugins.PaneType.BinderDesign, Crudspa.Content.Design.Client', 'Crudspa.Content.Display.Client.Plugins.PaneType.BinderDisplay, Crudspa.Content.Display.Client')
    ,('5244a27e-d872-4842-853a-0edd15aa0fad', 'Content | Blog - Display',                       'Crudspa.Content.Design.Client.Plugins.PaneType.BlogDesign, Crudspa.Content.Design.Client',   'Crudspa.Content.Display.Client.Plugins.PaneType.BlogDisplay, Crudspa.Content.Display.Client')
    ,('c0b77408-8ec0-4a1d-87f0-019e57a6da1c', 'Content | Blog - Edit',                          null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.BlogEdit, Crudspa.Content.Design.Client')
    ,('abe69d1b-52a7-43ef-af84-78e2af36c3fa', 'Content | Blog - List',                          null,                                                                                         'Crudspa.Content.Display.Client.Plugins.PaneType.BlogList, Crudspa.Content.Display.Client')
    ,('0cc00d0a-67ce-4069-9fb3-4df3bf3f0cc7', 'Content | Blog - List for Portal',               null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.BlogListForPortal, Crudspa.Content.Design.Client')
    ,('19e797d8-3380-4767-8878-a1c2775d732d', 'Content | Course - Display',                     'Crudspa.Content.Design.Client.Plugins.PaneType.CourseDesign, Crudspa.Content.Design.Client', 'Crudspa.Content.Display.Client.Plugins.PaneType.CourseDisplay, Crudspa.Content.Display.Client')
    ,('d6760dc1-6d4c-412e-a24c-c7bd8f6d6bca', 'Content | Course - Edit',                        null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.CourseEdit, Crudspa.Content.Design.Client')
    ,('4f843b6d-adba-4eb1-9899-2b70516d9ffa', 'Content | Course - List for Track',              null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.CourseListForTrack, Crudspa.Content.Design.Client')
    ,('7b918736-4df5-4d7d-8db8-4ba1686a84c7', 'Content | Course - Page Edit',                   null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.CoursePageEdit, Crudspa.Content.Design.Client')
    ,('e96f9f9f-8c79-46a9-9b5a-07f721b9ba21', 'Content | Course - Section Edit',                null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.CourseSectionEdit, Crudspa.Content.Design.Client')
    ,('c7dcfca8-bc1b-4d72-9799-0a2ee13d7f13', 'Content | Course - Sections',                    null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.CoursePageSections, Crudspa.Content.Design.Client')
    ,('d26484f8-b017-42f2-b963-600795d342aa', 'Content | Email - Edit',                         null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.EmailEdit, Crudspa.Content.Design.Client')
    ,('aeb0a3d0-c0d4-4a87-8d31-46038a4d4741', 'Content | Email - Find for Membership',          null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.EmailFindForMembership, Crudspa.Content.Design.Client')
    ,('212b4b11-6027-4f51-9a59-d36df3dc5d1f', 'Content | Email Template - Edit',                null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.EmailTemplateEdit, Crudspa.Content.Design.Client')
    ,('9bf4c6b4-2780-431c-9deb-bbc138833967', 'Content | Email Template - Find for Membership', null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.EmailTemplateFindForMembership, Crudspa.Content.Design.Client')
    ,('c5209476-2eee-4fce-bf11-dd50c996c347', 'Content | Font - Many for Portal',               null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.FontManyForPortal, Crudspa.Content.Design.Client')
    ,('313d7abf-1428-4a9f-a805-69d5b14c2c62', 'Content | Member - Edit',                        null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.MemberEdit, Crudspa.Content.Design.Client')
    ,('492dcc9e-ea4f-44de-bf16-a700a67352db', 'Content | Member - Find for Membership',         null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.MemberFindForMembership, Crudspa.Content.Design.Client')
    ,('25b8efd0-fd75-4b6a-86cb-f33e06186484', 'Content | Membership - Edit',                    null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.MembershipEdit, Crudspa.Content.Design.Client')
    ,('070a9ccf-6080-47f7-9c88-404f89d8a6ad', 'Content | Membership - List for Portal',         null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.MembershipListForPortal, Crudspa.Content.Design.Client')
    ,('33a466af-e9e1-42a7-ba1c-d5a09e854afe', 'Content | Page - Display',                       'Crudspa.Content.Design.Client.Plugins.PaneType.PageDesign, Crudspa.Content.Design.Client',   'Crudspa.Content.Display.Client.Plugins.PaneType.PageDisplay, Crudspa.Content.Display.Client')
    ,('86e4c5fc-97f2-4579-9de2-6920b0e82df9', 'Content | Page - List for Course',               null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.PageListForCourse, Crudspa.Content.Design.Client')
    ,('c96ab9bf-4074-444c-9702-64cacdc59171', 'Content | Pane - Page Edit',                     null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.PageEditForPane, Crudspa.Content.Design.Client')
    ,('96a0bafa-d81b-48b2-9578-2f57422c3855', 'Content | Pane - Section Edit',                  null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.PaneSectionEdit, Crudspa.Content.Design.Client')
    ,('f4e8247b-a01d-4f98-bf7c-3e5b483a65d7', 'Content | Pane - Sections',                      null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.PageSectionsForPane, Crudspa.Content.Design.Client')
    ,('6f8caf81-d904-4ee6-9767-0a1e5bcea651', 'Content | Portal - Edit',                        null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.ContentPortalEdit, Crudspa.Content.Design.Client')
    ,('f7ce9bf5-9771-4fce-bc03-512663c23561', 'Content | Portal - Section Edit',                null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.ContentPortalSectionEdit, Crudspa.Content.Design.Client')
    ,('76c202dc-aced-4718-a497-ac506fbff162', 'Content | Post - Display',                       'Crudspa.Content.Design.Client.Plugins.PaneType.PostDesign, Crudspa.Content.Design.Client',   'Crudspa.Content.Display.Client.Plugins.PaneType.PostDisplay, Crudspa.Content.Display.Client')
    ,('9eb8218a-ee51-4be7-afa3-e107cb408fee', 'Content | Post - Edit',                          null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.PostEdit, Crudspa.Content.Design.Client')
    ,('efceccc8-1515-435e-9714-6e519fba111e', 'Content | Post - Find for Blog',                 null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.PostFindForBlog, Crudspa.Content.Design.Client')
    ,('41f507c6-4a4d-47ec-a274-c8f0cc04a98c', 'Content | Post - Page Edit',                     null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.PostPageEdit, Crudspa.Content.Design.Client')
    ,('c14d936c-b023-47ac-9be5-96b372649ea1', 'Content | Post - Section Edit',                  null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.PostSectionEdit, Crudspa.Content.Design.Client')
    ,('4379ca08-fc0f-42f7-82fd-9ff066ee3701', 'Content | Style - Many for Portal',              null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.StyleManyForPortal, Crudspa.Content.Design.Client')
    ,('7b0e0f9d-1a67-4ff6-b4ec-2f4d56f7c2e1', 'Content | Style - Preview',                      null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.StylePreview, Crudspa.Content.Design.Client')
    ,('eb567d84-79e4-4137-85f2-63353dc07673', 'Content | Token - List for Membership',          null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.TokenListForMembership, Crudspa.Content.Design.Client')
    ,('799670a9-b527-4447-b646-6cfdef53570b', 'Content | Track - Display',                      'Crudspa.Content.Design.Client.Plugins.PaneType.TrackDesign, Crudspa.Content.Design.Client',  'Crudspa.Content.Display.Client.Plugins.PaneType.TrackDisplay, Crudspa.Content.Display.Client')
    ,('d82bbf64-6cec-4f62-8c28-d20539445a70', 'Content | Track - Edit',                         null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.TrackEdit, Crudspa.Content.Design.Client')
    ,('5f54c629-8c8c-4a1f-a2f3-7031e246b6d1', 'Content | Track - List',                         null,                                                                                         'Crudspa.Content.Display.Client.Plugins.PaneType.TrackList, Crudspa.Content.Display.Client')
    ,('d42fef67-13e0-4730-9fdc-74934a0652a7', 'Content | Track - List for Portal',              null,                                                                                         'Crudspa.Content.Design.Client.Plugins.PaneType.TrackListForPortal, Crudspa.Content.Design.Client')
    ,('f04dc913-e280-42f6-8f04-4885eb5e76a5', 'Framework | Account Settings',                   null,                                                                                         'Crudspa.Framework.Core.Client.Plugins.PaneType.AccountSettings, Crudspa.Framework.Core.Client')
    ,('7368a462-eaaf-4879-b65e-4a903732e82d', 'Framework | Job - Edit',                         null,                                                                                         'Crudspa.Framework.Jobs.Client.Plugins.PaneType.JobEdit, Crudspa.Framework.Jobs.Client')
    ,('a2b63c33-02f8-440d-a81e-0280261a3939', 'Framework | Job - Find',                         null,                                                                                         'Crudspa.Framework.Jobs.Client.Plugins.PaneType.JobFind, Crudspa.Framework.Jobs.Client')
    ,('5f6d5089-135e-43df-9a6d-1c495a82ee2b', 'Framework | Job Schedule - Edit',                null,                                                                                         'Crudspa.Framework.Jobs.Client.Plugins.PaneType.JobScheduleEdit, Crudspa.Framework.Jobs.Client')
    ,('ad39508d-d998-4621-9a7a-b439c7d3dbd7', 'Framework | Job Schedule - List',                null,                                                                                         'Crudspa.Framework.Jobs.Client.Plugins.PaneType.JobScheduleList, Crudspa.Framework.Jobs.Client')
    ,('95365eeb-00f9-4de7-a2e9-87f686c1e4df', 'Framework | Portal - Edit',                      null,                                                                                         'Crudspa.Framework.Core.Client.Plugins.PaneType.PortalEdit, Crudspa.Framework.Core.Client')
    ,('c04e5667-6824-4f42-9063-3b9a7b1809e9', 'Framework | Portal - List',                      null,                                                                                         'Crudspa.Framework.Core.Client.Plugins.PaneType.PortalList, Crudspa.Framework.Core.Client')
    ,('7f92e001-499b-44cc-a9bc-4020ca306d2a', 'Framework | Segment - Edit',                     null,                                                                                         'Crudspa.Framework.Core.Client.Plugins.PaneType.SegmentEdit, Crudspa.Framework.Core.Client')
    ,('9ce57b6b-4bb0-49b9-a35e-98d596f8f3a1', 'Framework | Segment - List for Parent',          null,                                                                                         'Crudspa.Framework.Core.Client.Plugins.PaneType.SegmentListForParent, Crudspa.Framework.Core.Client')
    ,('55d77a1c-97f7-424d-a107-ccf434e3fd43', 'Framework | Segment - List for Portal',          null,                                                                                         'Crudspa.Framework.Core.Client.Plugins.PaneType.SegmentListForPortal, Crudspa.Framework.Core.Client')
    ,('7c3bffad-e780-4575-acaf-50a7bcee52d6', 'Framework | Segment - Panes',                    null,                                                                                         'Crudspa.Framework.Core.Client.Plugins.PaneType.SegmentPanes, Crudspa.Framework.Core.Client')
) as Source
    (Id, Name, EditorView, DisplayView)
on Target.Id = Source.Id

when matched then
update set
     Target.IsDeleted = 0
    ,Target.Name = Source.Name
    ,Target.EditorView = Source.EditorView
    ,Target.DisplayView = Source.DisplayView

when not matched by target then
insert (Id, Name, EditorView, DisplayView)
values (Id, Name, EditorView, DisplayView)

when not matched by source and Target.IsDeleted = 0 then
update set
     Target.IsDeleted = 1
;