create table [Framework].[ImageFile] (
    [Id] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [BlobId] uniqueidentifier not null,
    [Name] nvarchar(150) not null,
    [Format] nvarchar(10) not null,
    [Width] int null,
    [Height] int null,
    [Caption] nvarchar(max) null,
    [OptimizedStatus] int default(0) not null,
    [OptimizedBlobId] uniqueidentifier null,
    [OptimizedFormat] nvarchar(10) null,
    [OptimizedBatchId] uniqueidentifier null,
    [Resized96BlobId] uniqueidentifier null,
    [Resized192BlobId] uniqueidentifier null,
    [Resized360BlobId] uniqueidentifier null,
    [Resized540BlobId] uniqueidentifier null,
    [Resized720BlobId] uniqueidentifier null,
    [Resized1080BlobId] uniqueidentifier null,
    [Resized1440BlobId] uniqueidentifier null,
    [Resized1920BlobId] uniqueidentifier null,
    [Resized3840BlobId] uniqueidentifier null,
    constraint [PK_Framework_ImageFile] primary key clustered ([Id]),
);