create table [Framework].[Job] (
    [Id] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [TypeId] uniqueidentifier not null,
    [Config] nvarchar(max) not null,
    [Description] nvarchar(max) not null,
    [Added] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [Started] datetimeoffset(7) null,
    [Ended] datetimeoffset(7) null,
    [StatusId] uniqueidentifier not null,
    [DeviceId] uniqueidentifier null,
    [ScheduleId] uniqueidentifier null,
    [BatchId] uniqueidentifier null,
    constraint [PK_Framework_Job] primary key clustered ([Id]),
    constraint [FK_Framework_Job_Type] foreign key ([TypeId]) references [Framework].[JobType] ([Id]),
    constraint [FK_Framework_Job_Status] foreign key ([StatusId]) references [Framework].[JobStatus] ([Id]),
    constraint [FK_Framework_Job_Device] foreign key ([DeviceId]) references [Framework].[Device] ([Id]),
    constraint [FK_Framework_Job_Schedule] foreign key ([ScheduleId]) references [Framework].[JobSchedule] ([Id]),
);