create table [Framework].[JobSchedule] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [Name] nvarchar(50) not null,
    [TypeId] uniqueidentifier not null,
    [Config] nvarchar(max) not null,
    [Description] nvarchar(max) not null,
    [DeviceId] uniqueidentifier null,
    [RecurrenceAmount] int not null,
    [RecurrenceInterval] int default(0) not null,
    [RecurrencePattern] int default(0) not null,
    [Day] int null,
    [DayOfWeek] int default(0) not null,
    [Hour] int null,
    [Minute] int null,
    [Second] int null,
    [TimeZoneId] nvarchar(32) null,
    [NextRun] datetimeoffset(7) default(sysdatetimeoffset()) null,
    constraint [PK_Framework_JobSchedule] primary key clustered ([Id]),
    constraint [FK_Framework_JobSchedule_Type] foreign key ([TypeId]) references [Framework].[JobType] ([Id]),
    constraint [FK_Framework_JobSchedule_Device] foreign key ([DeviceId]) references [Framework].[Device] ([Id]),
);