create table [Framework].[Segment] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [Key] nvarchar(100) not null,
    [Title] nvarchar(150) not null,
    [StatusId] uniqueidentifier not null,
    [Fixed] bit not null,
    [RequiresId] bit not null,
    [PortalId] uniqueidentifier not null,
    [TypeId] uniqueidentifier not null,
    [PermissionId] uniqueidentifier null,
    [IconId] uniqueidentifier null,
    [ParentId] uniqueidentifier null,
    [Recursive] bit default(0) not null,
    [Vertical] bit default(0) not null,
    [ConfigJson] nvarchar(max) null,
    [AllLicenses] bit default(1) not null,
    [Ordinal] int not null,
    constraint [PK_Framework_Segment] primary key clustered ([Id]),
    constraint [FK_Framework_Segment_Status] foreign key ([StatusId]) references [Framework].[ContentStatus] ([Id]),
    constraint [FK_Framework_Segment_Portal] foreign key ([PortalId]) references [Framework].[Portal] ([Id]),
    constraint [FK_Framework_Segment_Type] foreign key ([TypeId]) references [Framework].[SegmentType] ([Id]),
    constraint [FK_Framework_Segment_Permission] foreign key ([PermissionId]) references [Framework].[Permission] ([Id]),
    constraint [FK_Framework_Segment_Icon] foreign key ([IconId]) references [Framework].[Icon] ([Id]),
    constraint [FK_Framework_Segment_Parent] foreign key ([ParentId]) references [Framework].[Segment] ([Id]),
);