<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Crudspa.Framework.Auth.Shared</AssemblyName>
    <RootNamespace>Crudspa.Framework.Auth.Shared</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\Shared\Shared.csproj" />
  </ItemGroup>
</Project>