create table [Education].[ActivityType] (
    [Id] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [Name] nvarchar(100) not null,
    [Key] nvarchar(100) not null,
    [DisplayView] nvarchar(150) not null,
    [CategoryId] uniqueidentifier not null,
    [StatusId] uniqueidentifier not null,
    [ContextGuidance] nvarchar(250) null,
    [ChoiceGuidance] nvarchar(250) null,
    [ExtraGuidance] nvarchar(250) null,
    [SupportsContextText] bit default(0) not null,
    [RequiresContextText] bit default(0) not null,
    [SupportsContextAudio] bit default(0) not null,
    [RequiresContextAudio] bit default(0) not null,
    [SupportsContextImage] bit default(0) not null,
    [RequiresContextImage] bit default(0) not null,
    [SupportsExtraText] bit default(0) not null,
    [RequiresExtraText] bit default(0) not null,
    [SupportsChoices] bit default(0) not null,
    [RequiresCorrectChoices] bit default(0) not null,
    [SupportsAudioChoices] bit default(0) not null,
    [RequiresAudioChoices] bit default(0) not null,
    [RequiresDataChoices] bit default(0) not null,
    [RequiresImageChoices] bit default(0) not null,
    [SupportsTextChoices] bit default(0) not null,
    [RequiresTextChoices] bit default(0) not null,
    [RequiresLongerTextChoices] bit default(0) not null,
    [RequiresColumnOrdinal] bit default(0) not null,
    [RequiresTextOrImageChoices] bit default(0) not null,
    [MinChoices] int not null,
    [MaxChoices] int not null,
    [MinCorrectChoices] int not null,
    [MaxCorrectChoices] int not null,
    [ShuffleChoices] bit default(1) not null,
    constraint [PK_Education_ActivityType] primary key clustered ([Id]),
    constraint [FK_Education_ActivityType_Category] foreign key ([CategoryId]) references [Education].[ActivityCategory] ([Id]),
    constraint [FK_Education_ActivityType_Status] foreign key ([StatusId]) references [Education].[ActivityTypeStatus] ([Id]),
);