create table [Education].[Activity] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [Key] nvarchar(100) null,
    [ActivityTypeId] uniqueidentifier not null,
    [ContentAreaId] uniqueidentifier not null,
    [StatusId] uniqueidentifier not null,
    [ContextText] nvarchar(max) null,
    [ContextAudioFileId] uniqueidentifier null,
    [ContextImageFileId] uniqueidentifier null,
    [ExtraText] nvarchar(max) null,
    constraint [PK_Education_Activity] primary key clustered ([Id]),
    constraint [FK_Education_Activity_ActivityType] foreign key ([ActivityTypeId]) references [Education].[ActivityType] ([Id]),
    constraint [FK_Education_Activity_ContentArea] foreign key ([ContentAreaId]) references [Education].[ContentArea] ([Id]),
    constraint [FK_Education_Activity_Status] foreign key ([StatusId]) references [Education].[ActivityStatus] ([Id]),
    constraint [FK_Education_Activity_ContextAudioFile] foreign key ([ContextAudioFileId]) references [Framework].[AudioFile] ([Id]),
    constraint [FK_Education_Activity_ContextImageFile] foreign key ([ContextImageFileId]) references [Framework].[ImageFile] ([Id]),
);