create table [Education].[Assessment] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [OwnerId] uniqueidentifier not null,
    [Name] nvarchar(100) not null,
    [StatusId] uniqueidentifier not null,
    [AvailableStart] date default(convert(date, sysdatetime())) not null,
    [AvailableEnd] date default(convert(date, sysdatetime())) not null,
    [GradeId] uniqueidentifier not null,
    [CategoryId] uniqueidentifier null,
    [ImageFileId] uniqueidentifier null,
    constraint [PK_Education_Assessment] primary key clustered ([Id]),
    constraint [FK_Education_Assessment_Owner] foreign key ([OwnerId]) references [Framework].[Organization] ([Id]),
    constraint [FK_Education_Assessment_Status] foreign key ([StatusId]) references [Framework].[ContentStatus] ([Id]),
    constraint [FK_Education_Assessment_Grade] foreign key ([GradeId]) references [Education].[Grade] ([Id]),
    constraint [FK_Education_Assessment_Category] foreign key ([CategoryId]) references [Education].[ContentCategory] ([Id]),
    constraint [FK_Education_Assessment_ImageFile] foreign key ([ImageFileId]) references [Framework].[ImageFile] ([Id]),
);