create table [Education].[Book] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [OwnerId] uniqueidentifier not null,
    [Key] nvarchar(100) not null,
    [Isbn] nvarchar(20) not null,
    [Title] nvarchar(150) not null,
    [Author] nvarchar(150) not null,
    [Lexile] nvarchar(10) not null,
    [SeasonId] uniqueidentifier not null,
    [StatusId] uniqueidentifier null, --todo: Remove after initial deploy
    [ContentStatusId] uniqueidentifier null, --todo: Make non-nullable and rename after initial deploy
    [Summary] nvarchar(max) null,
    [CoverImageId] uniqueidentifier not null,
    [ShowOnline] bit default(0) not null,
    [YouTubeId] nvarchar(20) null,
    [SongAudioFileId] uniqueidentifier null,
    [CategoryId] uniqueidentifier null,
    [IntroVideoId] uniqueidentifier null,
    [ReadAloudVideoId] uniqueidentifier null,
    [PrefaceBinderId] uniqueidentifier null,
    [GuideImageId] uniqueidentifier null,
    [RequiresAchievementId] uniqueidentifier null,
    constraint [PK_Education_Book] primary key clustered ([Id]),
    constraint [FK_Education_Book_Owner] foreign key ([OwnerId]) references [Framework].[Organization] ([Id]),
    constraint [FK_Education_Book_Season] foreign key ([SeasonId]) references [Education].[BookSeason] ([Id]),
    constraint [FK_Education_Book_Status] foreign key ([StatusId]) references [Education].[BookStatus] ([Id]),
    constraint [FK_Education_Book_ContentStatus] foreign key ([ContentStatusId]) references [Framework].[ContentStatus] ([Id]),
    constraint [FK_Education_Book_CoverImage] foreign key ([CoverImageId]) references [Framework].[ImageFile] ([Id]),
    constraint [FK_Education_Book_SongAudioFile] foreign key ([SongAudioFileId]) references [Framework].[AudioFile] ([Id]),
    constraint [FK_Education_Book_Category] foreign key ([CategoryId]) references [Education].[BookCategory] ([Id]),
    constraint [FK_Education_Book_IntroVideo] foreign key ([IntroVideoId]) references [Framework].[VideoFile] ([Id]),
    constraint [FK_Education_Book_ReadAloudVideo] foreign key ([ReadAloudVideoId]) references [Framework].[VideoFile] ([Id]),
    constraint [FK_Education_Book_PrefaceBinder] foreign key ([PrefaceBinderId]) references [Content].[Binder] ([Id]),
    constraint [FK_Education_Book_GuideImage] foreign key ([GuideImageId]) references [Framework].[ImageFile] ([Id]),
    constraint [FK_Education_Book_RequiresAchievement] foreign key ([RequiresAchievementId]) references [Education].[Achievement] ([Id]),
);