create table [Education].[Classroom] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [OrganizationId] uniqueidentifier not null,
    [SchoolId] uniqueidentifier not null,
    [GradeId] uniqueidentifier null,
    [SchoolYearId] uniqueidentifier not null,
    [TypeId] uniqueidentifier null,
    [ImportNum] int null,
    [SmallClassroom] bit default(0) not null,
    constraint [PK_Education_Classroom] primary key clustered ([Id]),
    constraint [FK_Education_Classroom_Organization] foreign key ([OrganizationId]) references [Framework].[Organization] ([Id]),
    constraint [FK_Education_Classroom_School] foreign key ([SchoolId]) references [Education].[School] ([Id]),
    constraint [FK_Education_Classroom_Grade] foreign key ([GradeId]) references [Education].[Grade] ([Id]),
    constraint [FK_Education_Classroom_SchoolYear] foreign key ([SchoolYearId]) references [Education].[SchoolYear] ([Id]),
    constraint [FK_Education_Classroom_Type] foreign key ([TypeId]) references [Education].[ClassroomType] ([Id]),
);