create table [Education].[ClassRecording] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [AudioFileId] uniqueidentifier null,
    [ImageId] uniqueidentifier null,
    [Uploaded] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UploadedBy] uniqueidentifier not null,
    [CategoryId] uniqueidentifier not null,
    [Unit] int null,
    [Lesson] int null,
    [TeacherNotes] nvarchar(max) null,
    constraint [PK_Education_ClassRecording] primary key clustered ([Id]),
    constraint [FK_Education_ClassRecording_AudioFile] foreign key ([AudioFileId]) references [Framework].[AudioFile] ([Id]),
    constraint [FK_Education_ClassRecording_Image] foreign key ([ImageId]) references [Framework].[ImageFile] ([Id]),
    constraint [FK_Education_ClassRecording_UploadedBy] foreign key ([UploadedBy]) references [Education].[SchoolContact] ([Id]),
    constraint [FK_Education_ClassRecording_Category] foreign key ([CategoryId]) references [Education].[ContentCategory] ([Id]),
);