create table [Education].[FamilyMember] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [FamilyId] uniqueidentifier not null,
    [TypeId] uniqueidentifier not null,
    [ContactId] uniqueidentifier null,
    [Culture] nvarchar(5) not null,
    [SmsOptOut] bit default(0) not null,
    [PhoneChanged] bit default(0) not null,
    [BookGoal] int null,
    [ImportNum] int null,
    [SurveyLink] nvarchar(250) null,
    constraint [PK_Education_FamilyMember] primary key clustered ([Id]),
    constraint [FK_Education_FamilyMember_Family] foreign key ([FamilyId]) references [Education].[Family] ([Id]),
    constraint [FK_Education_FamilyMember_Type] foreign key ([TypeId]) references [Education].[FamilyMemberType] ([Id]),
    constraint [FK_Education_FamilyMember_Contact] foreign key ([ContactId]) references [Framework].[Contact] ([Id]),
);