create table [Education].[Game] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [BookId] uniqueidentifier not null,
    [Key] nvarchar(75) not null,
    [Title] nvarchar(75) not null,
    [IconName] nvarchar(75) null,
    [IconId] uniqueidentifier null,
    [StatusId] uniqueidentifier not null,
    [GradeId] uniqueidentifier not null,
    [AssessmentLevelId] uniqueidentifier not null,
    [RequiresAchievementId] uniqueidentifier null,
    [GeneratesAchievementId] uniqueidentifier null,
    constraint [PK_Education_Game] primary key clustered ([Id]),
    constraint [FK_Education_Game_Book] foreign key ([BookId]) references [Education].[Book] ([Id]),
    constraint [FK_Education_Game_Icon] foreign key ([IconId]) references [Framework].[Icon] ([Id]),
    constraint [FK_Education_Game_Status] foreign key ([StatusId]) references [Framework].[ContentStatus] ([Id]),
    constraint [FK_Education_Game_Grade] foreign key ([GradeId]) references [Education].[Grade] ([Id]),
    constraint [FK_Education_Game_AssessmentLevel] foreign key ([AssessmentLevelId]) references [Education].[AssessmentLevel] ([Id]),
    constraint [FK_Education_Game_RequiresAchievement] foreign key ([RequiresAchievementId]) references [Education].[Achievement] ([Id]),
    constraint [FK_Education_Game_GeneratesAchievement] foreign key ([GeneratesAchievementId]) references [Education].[Achievement] ([Id]),
);