create table [Education].[GameActivity] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [SectionId] uniqueidentifier not null,
    [ActivityId] uniqueidentifier not null,
    [ThemeWord] nvarchar(50) null,
    [Rigorous] bit default(0) not null,
    [Multisyllabic] bit default(0) not null,
    [GroupId] uniqueidentifier null,
    [TypeId] uniqueidentifier not null,
    [Ordinal] int not null,
    constraint [PK_Education_GameActivity] primary key clustered ([Id]),
    constraint [FK_Education_GameActivity_Section] foreign key ([SectionId]) references [Education].[GameSection] ([Id]),
    constraint [FK_Education_GameActivity_Activity] foreign key ([ActivityId]) references [Education].[Activity] ([Id]),
    constraint [FK_Education_GameActivity_Group] foreign key ([GroupId]) references [Education].[ResearchGroup] ([Id]),
    constraint [FK_Education_GameActivity_Type] foreign key ([TypeId]) references [Education].[GameActivityType] ([Id]),
);