create table [Education].[Lesson] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [Title] nvarchar(75) not null,
    [StatusId] uniqueidentifier not null,
    [UnitId] uniqueidentifier not null,
    [ImageId] uniqueidentifier not null,
    [GuideImageId] uniqueidentifier null,
    [GuideText] nvarchar(max) null,
    [GuideAudioId] uniqueidentifier null,
    [RequiresAchievementId] uniqueidentifier null,
    [GeneratesAchievementId] uniqueidentifier null,
    [RequireSequentialCompletion] bit default(1) not null,
    [Treatment] bit default(1) not null,
    [Control] bit default(1) not null,
    [Ordinal] int not null,
    constraint [PK_Education_Lesson] primary key clustered ([Id]),
    constraint [FK_Education_Lesson_Status] foreign key ([StatusId]) references [Framework].[ContentStatus] ([Id]),
    constraint [FK_Education_Lesson_Unit] foreign key ([UnitId]) references [Education].[Unit] ([Id]),
    constraint [FK_Education_Lesson_Image] foreign key ([ImageId]) references [Framework].[ImageFile] ([Id]),
    constraint [FK_Education_Lesson_GuideImage] foreign key ([GuideImageId]) references [Framework].[ImageFile] ([Id]),
    constraint [FK_Education_Lesson_GuideAudio] foreign key ([GuideAudioId]) references [Framework].[AudioFile] ([Id]),
    constraint [FK_Education_Lesson_RequiresAchievement] foreign key ([RequiresAchievementId]) references [Education].[Achievement] ([Id]),
    constraint [FK_Education_Lesson_GeneratesAchievement] foreign key ([GeneratesAchievementId]) references [Education].[Achievement] ([Id]),
);