create table [Education].[ListenQuestion] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [ListenPartId] uniqueidentifier not null,
    [Text] nvarchar(max) not null,
    [AudioFileId] uniqueidentifier null,
    [IsPreview] bit default(0) not null,
    [PageBreakBefore] bit default(0) not null,
    [HasCorrectChoice] bit default(0) not null,
    [RequireTextInput] bit default(0) not null,
    [CategoryId] uniqueidentifier not null,
    [ImageFileId] uniqueidentifier null,
    [TypeId] uniqueidentifier not null,
    [Ordinal] int not null,
    constraint [PK_Education_ListenQuestion] primary key clustered ([Id]),
    constraint [FK_Education_ListenQuestion_ListenPart] foreign key ([ListenPartId]) references [Education].[ListenPart] ([Id]),
    constraint [FK_Education_ListenQuestion_AudioFile] foreign key ([AudioFileId]) references [Framework].[AudioFile] ([Id]),
    constraint [FK_Education_ListenQuestion_Category] foreign key ([CategoryId]) references [Education].[ListenQuestionCategory] ([Id]),
    constraint [FK_Education_ListenQuestion_ImageFile] foreign key ([ImageFileId]) references [Framework].[ImageFile] ([Id]),
    constraint [FK_Education_ListenQuestion_Type] foreign key ([TypeId]) references [Education].[ReadQuestionType] ([Id]),
);