create table [Education].[Objective] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [Title] nvarchar(75) not null,
    [StatusId] uniqueidentifier not null,
    [LessonId] uniqueidentifier not null,
    [TrophyImageId] uniqueidentifier not null,
    [BinderId] uniqueidentifier not null,
    [RequiresAchievementId] uniqueidentifier null,
    [GeneratesAchievementId] uniqueidentifier null,
    [Ordinal] int not null,
    constraint [PK_Education_Objective] primary key clustered ([Id]),
    constraint [FK_Education_Objective_Status] foreign key ([StatusId]) references [Framework].[ContentStatus] ([Id]),
    constraint [FK_Education_Objective_Lesson] foreign key ([LessonId]) references [Education].[Lesson] ([Id]),
    constraint [FK_Education_Objective_TrophyImage] foreign key ([TrophyImageId]) references [Framework].[ImageFile] ([Id]),
    constraint [FK_Education_Objective_Binder] foreign key ([BinderId]) references [Content].[Binder] ([Id]),
    constraint [FK_Education_Objective_RequiresAchievement] foreign key ([RequiresAchievementId]) references [Education].[Achievement] ([Id]),
    constraint [FK_Education_Objective_GeneratesAchievement] foreign key ([GeneratesAchievementId]) references [Education].[Achievement] ([Id]),
);