create table [Education].[Post] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [ForumId] uniqueidentifier null,
    [ParentId] uniqueidentifier null,
    [Pinned] bit default(0) not null,
    [Body] nvarchar(max) not null,
    [AudioId] uniqueidentifier null,
    [ImageId] uniqueidentifier null,
    [PdfId] uniqueidentifier null,
    [VideoId] uniqueidentifier null,
    [ById] uniqueidentifier not null,
    [ByOrganizationName] nvarchar(75) not null,
    [Posted] datetimeoffset(7) not null,
    [Edited] datetimeoffset(7) null,
    [Type] int null,
    [GradeId] uniqueidentifier null,
    [SubjectId] uniqueidentifier null,
    constraint [PK_Education_Post] primary key clustered ([Id]),
    constraint [FK_Education_Post_Forum] foreign key ([ForumId]) references [Education].[Forum] ([Id]),
    constraint [FK_Education_Post_Parent] foreign key ([ParentId]) references [Education].[Post] ([Id]),
    constraint [FK_Education_Post_Audio] foreign key ([AudioId]) references [Framework].[AudioFile] ([Id]),
    constraint [FK_Education_Post_Image] foreign key ([ImageId]) references [Framework].[ImageFile] ([Id]),
    constraint [FK_Education_Post_Pdf] foreign key ([PdfId]) references [Framework].[PdfFile] ([Id]),
    constraint [FK_Education_Post_Video] foreign key ([VideoId]) references [Framework].[VideoFile] ([Id]),
    constraint [FK_Education_Post_By] foreign key ([ById]) references [Framework].[Contact] ([Id]),
    constraint [FK_Education_Post_Grade] foreign key ([GradeId]) references [Education].[Grade] ([Id]),
    constraint [FK_Education_Post_Subject] foreign key ([SubjectId]) references [Education].[ClassroomType] ([Id]),
);