create table [Education].[ReadQuestion] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [ReadPartId] uniqueidentifier not null,
    [Text] nvarchar(max) not null,
    [AudioFileId] uniqueidentifier null,
    [IsPreview] bit default(0) not null,
    [PageBreakBefore] bit default(0) not null,
    [HasCorrectChoice] bit default(0) not null,
    [RequireTextInput] bit default(0) not null,
    [TypeId] uniqueidentifier not null,
    [CategoryId] uniqueidentifier not null,
    [ImageFileId] uniqueidentifier null,
    [Ordinal] int not null,
    constraint [PK_Education_ReadQuestion] primary key clustered ([Id]),
    constraint [FK_Education_ReadQuestion_ReadPart] foreign key ([ReadPartId]) references [Education].[ReadPart] ([Id]),
    constraint [FK_Education_ReadQuestion_AudioFile] foreign key ([AudioFileId]) references [Framework].[AudioFile] ([Id]),
    constraint [FK_Education_ReadQuestion_Type] foreign key ([TypeId]) references [Education].[ReadQuestionType] ([Id]),
    constraint [FK_Education_ReadQuestion_Category] foreign key ([CategoryId]) references [Education].[ReadQuestionCategory] ([Id]),
    constraint [FK_Education_ReadQuestion_ImageFile] foreign key ([ImageFileId]) references [Framework].[ImageFile] ([Id]),
);