create table [Education].[School] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [OrganizationId] uniqueidentifier not null,
    [DistrictId] uniqueidentifier not null,
    [CommunityId] uniqueidentifier null,
    [AddressId] uniqueidentifier null,
    [Key] nvarchar(100) not null,
    [ImportNum] int null,
    [Treatment] bit default(0) not null,
    [ResearchGroupId] uniqueidentifier null,
    constraint [PK_Education_School] primary key clustered ([Id]),
    constraint [FK_Education_School_Organization] foreign key ([OrganizationId]) references [Framework].[Organization] ([Id]),
    constraint [FK_Education_School_District] foreign key ([DistrictId]) references [Education].[District] ([Id]),
    constraint [FK_Education_School_Community] foreign key ([CommunityId]) references [Education].[Community] ([Id]),
    constraint [FK_Education_School_Address] foreign key ([AddressId]) references [Framework].[UsaPostal] ([Id]),
    constraint [FK_Education_School_ResearchGroup] foreign key ([ResearchGroupId]) references [Education].[ResearchGroup] ([Id]),
);