create table [Education].[SchoolContact] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [SchoolId] uniqueidentifier not null,
    [ContactId] uniqueidentifier not null,
    [UserId] uniqueidentifier null,
    [TitleId] uniqueidentifier not null,
    [TestAccount] bit default(0) not null,
    [Treatment] bit default(0) not null,
    [IdNumber] nvarchar(35) null,
    [ResearchGroupId] uniqueidentifier null,
    constraint [PK_Education_SchoolContact] primary key clustered ([Id]),
    constraint [FK_Education_SchoolContact_School] foreign key ([SchoolId]) references [Education].[School] ([Id]),
    constraint [FK_Education_SchoolContact_Contact] foreign key ([ContactId]) references [Framework].[Contact] ([Id]),
    constraint [FK_Education_SchoolContact_User] foreign key ([UserId]) references [Framework].[User] ([Id]),
    constraint [FK_Education_SchoolContact_Title] foreign key ([TitleId]) references [Education].[Title] ([Id]),
    constraint [FK_Education_SchoolContact_ResearchGroup] foreign key ([ResearchGroupId]) references [Education].[ResearchGroup] ([Id]),
);