create table [Education].[Student] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [ResearchId] nvarchar(100) null,
    [ContactId] uniqueidentifier not null,
    [UserId] uniqueidentifier null,
    [FamilyId] uniqueidentifier not null,
    [StatusId] uniqueidentifier not null,
    [SecretCode] nvarchar(75) null,
    [GenderId] uniqueidentifier null,
    [GradeId] uniqueidentifier not null,
    [AssessmentTypeGroupId] uniqueidentifier not null,
    [AssessmentLevelGroupId] uniqueidentifier not null,
    [ConditionGroupId] uniqueidentifier not null,
    [GoalSettingGroupId] uniqueidentifier not null,
    [PersonalizationGroupId] uniqueidentifier not null,
    [ContentGroupId] uniqueidentifier not null,
    [AudioGenderId] uniqueidentifier not null,
    [ChallengeLevelId] uniqueidentifier not null,
    [MoreSample] bit default(1) not null,
    [TextSample] bit default(1) not null,
    [PreferredName] nvarchar(75) null,
    [AvatarGraphicId] uniqueidentifier null,
    [AvatarColor] nvarchar(10) null,
    [AvatarCharacter] int null,
    [AvatarString] nvarchar(2) null,
    [TermsAccepted] datetimeoffset(7) null,
    [IdNumber] nvarchar(35) null,
    [CreatedBySchool] bit default(0) not null,
    [DeletedBySchool] bit default(0) not null,
    [IsTestAccount] bit default(0) not null,
    [ResearchGroupId] uniqueidentifier null,
    constraint [PK_Education_Student] primary key clustered ([Id]),
    constraint [FK_Education_Student_Contact] foreign key ([ContactId]) references [Framework].[Contact] ([Id]),
    constraint [FK_Education_Student_User] foreign key ([UserId]) references [Framework].[User] ([Id]),
    constraint [FK_Education_Student_Family] foreign key ([FamilyId]) references [Education].[Family] ([Id]),
    constraint [FK_Education_Student_Status] foreign key ([StatusId]) references [Education].[StudentStatus] ([Id]),
    constraint [FK_Education_Student_Gender] foreign key ([GenderId]) references [Education].[Gender] ([Id]),
    constraint [FK_Education_Student_Grade] foreign key ([GradeId]) references [Education].[Grade] ([Id]),
    constraint [FK_Education_Student_AssessmentTypeGroup] foreign key ([AssessmentTypeGroupId]) references [Education].[AssessmentType] ([Id]),
    constraint [FK_Education_Student_AssessmentLevelGroup] foreign key ([AssessmentLevelGroupId]) references [Education].[AssessmentLevel] ([Id]),
    constraint [FK_Education_Student_ConditionGroup] foreign key ([ConditionGroupId]) references [Education].[ConditionGroup] ([Id]),
    constraint [FK_Education_Student_GoalSettingGroup] foreign key ([GoalSettingGroupId]) references [Education].[GoalSettingGroup] ([Id]),
    constraint [FK_Education_Student_PersonalizationGroup] foreign key ([PersonalizationGroupId]) references [Education].[PersonalizationGroup] ([Id]),
    constraint [FK_Education_Student_ContentGroup] foreign key ([ContentGroupId]) references [Education].[ContentGroup] ([Id]),
    constraint [FK_Education_Student_AudioGender] foreign key ([AudioGenderId]) references [Education].[AudioGender] ([Id]),
    constraint [FK_Education_Student_ChallengeLevel] foreign key ([ChallengeLevelId]) references [Education].[ChallengeLevel] ([Id]),
    constraint [FK_Education_Student_ResearchGroup] foreign key ([ResearchGroupId]) references [Education].[ResearchGroup] ([Id]),
);