create table [Education].[Trifold] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [Title] nvarchar(75) not null,
    [BookId] uniqueidentifier not null,
    [StatusId] uniqueidentifier not null,
    [BinderId] uniqueidentifier not null,
    [RequiresAchievementId] uniqueidentifier null,
    [GeneratesAchievementId] uniqueidentifier null,
    [Ordinal] int not null,
    constraint [PK_Education_Trifold] primary key clustered ([Id]),
    constraint [FK_Education_Trifold_Book] foreign key ([BookId]) references [Education].[Book] ([Id]),
    constraint [FK_Education_Trifold_Status] foreign key ([StatusId]) references [Framework].[ContentStatus] ([Id]),
    constraint [FK_Education_Trifold_Binder] foreign key ([BinderId]) references [Content].[Binder] ([Id]),
    constraint [FK_Education_Trifold_RequiresAchievement] foreign key ([RequiresAchievementId]) references [Education].[Achievement] ([Id]),
    constraint [FK_Education_Trifold_GeneratesAchievement] foreign key ([GeneratesAchievementId]) references [Education].[Achievement] ([Id]),
);