create table [Education].[Unit] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [OwnerId] uniqueidentifier not null,
    [Title] nvarchar(75) not null,
    [StatusId] uniqueidentifier not null,
    [GradeId] uniqueidentifier not null,
    [ParentId] uniqueidentifier null,
    [ImageId] uniqueidentifier not null,
    [IntroAudioId] uniqueidentifier null,
    [SongAudioId] uniqueidentifier null,
    [GuideText] nvarchar(max) null,
    [GuideAudioId] uniqueidentifier null,
    [RequiresAchievementId] uniqueidentifier null,
    [GeneratesAchievementId] uniqueidentifier null,
    [Treatment] bit default(1) not null,
    [Control] bit default(1) not null,
    [Ordinal] int not null,
    constraint [PK_Education_Unit] primary key clustered ([Id]),
    constraint [FK_Education_Unit_Owner] foreign key ([OwnerId]) references [Framework].[Organization] ([Id]),
    constraint [FK_Education_Unit_Status] foreign key ([StatusId]) references [Framework].[ContentStatus] ([Id]),
    constraint [FK_Education_Unit_Grade] foreign key ([GradeId]) references [Education].[Grade] ([Id]),
    constraint [FK_Education_Unit_Parent] foreign key ([ParentId]) references [Education].[Unit] ([Id]),
    constraint [FK_Education_Unit_Image] foreign key ([ImageId]) references [Framework].[ImageFile] ([Id]),
    constraint [FK_Education_Unit_IntroAudio] foreign key ([IntroAudioId]) references [Framework].[AudioFile] ([Id]),
    constraint [FK_Education_Unit_SongAudio] foreign key ([SongAudioId]) references [Framework].[AudioFile] ([Id]),
    constraint [FK_Education_Unit_GuideAudio] foreign key ([GuideAudioId]) references [Framework].[AudioFile] ([Id]),
    constraint [FK_Education_Unit_RequiresAchievement] foreign key ([RequiresAchievementId]) references [Education].[Achievement] ([Id]),
    constraint [FK_Education_Unit_GeneratesAchievement] foreign key ([GeneratesAchievementId]) references [Education].[Achievement] ([Id]),
);