create table [Content].[Box] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [BackgroundColor] nvarchar(10) null,
    [BackgroundImageId] uniqueidentifier null,
    [BorderColor] nvarchar(10) null,
    [BorderRadius] nvarchar(10) null,
    [BorderThickness] nvarchar(10) null,
    [BorderThicknessTop] nvarchar(10) null,
    [BorderThicknessLeft] nvarchar(10) null,
    [BorderThicknessRight] nvarchar(10) null,
    [BorderThicknessBottom] nvarchar(10) null,
    [CustomFontIndex] int default(0) not null,
    [FontSize] nvarchar(10) null,
    [FontWeight] nvarchar(10) null,
    [ForegroundColor] nvarchar(10) null,
    [MarginBottom] nvarchar(10) null,
    [MarginLeft] nvarchar(10) null,
    [MarginRight] nvarchar(10) null,
    [MarginTop] nvarchar(10) null,
    [PaddingBottom] nvarchar(10) null,
    [PaddingLeft] nvarchar(10) null,
    [PaddingRight] nvarchar(10) null,
    [PaddingTop] nvarchar(10) null,
    [ShadowBlurRadius] nvarchar(10) null,
    [ShadowColor] nvarchar(10) null,
    [ShadowOffsetX] nvarchar(10) null,
    [ShadowOffsetY] nvarchar(10) null,
    [ShadowSpreadRadius] nvarchar(10) null,
    [TextShadowBlurRadius] nvarchar(10) null,
    [TextShadowColor] nvarchar(10) null,
    [TextShadowOffsetX] nvarchar(10) null,
    [TextShadowOffsetY] nvarchar(10) null,
    [HeadingLineHeight] nvarchar(10) null,
    [ParagraphLineHeight] nvarchar(10) null,
    constraint [PK_Content_Box] primary key clustered ([Id]),
    constraint [FK_Content_Box_BackgroundImage] foreign key ([BackgroundImageId]) references [Framework].[ImageFile] ([Id]),
);