create table [Content].[Button] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [Internal] bit default(1) not null,
    [Path] nvarchar(250) not null,
    [Text] nvarchar(250) null,
    [TextAlignIndex] int null,
    [LeftIconId] uniqueidentifier null,
    [RightIconId] uniqueidentifier null,
    [BoxId] uniqueidentifier null,
    [ShapeIndex] int default(0) not null,
    [GraphicIndex] int default(1) not null,
    [TextTypeIndex] int default(1) not null,
    [OrientationIndex] int default(0) not null,
    [IconId] uniqueidentifier null,
    [ImageId] uniqueidentifier null,
    constraint [PK_Content_Button] primary key clustered ([Id]),
    constraint [FK_Content_Button_LeftIcon] foreign key ([LeftIconId]) references [Framework].[Icon] ([Id]),
    constraint [FK_Content_Button_RightIcon] foreign key ([RightIconId]) references [Framework].[Icon] ([Id]),
    constraint [FK_Content_Button_Box] foreign key ([BoxId]) references [Content].[Box] ([Id]),
    constraint [FK_Content_Button_Icon] foreign key ([IconId]) references [Framework].[Icon] ([Id]),
    constraint [FK_Content_Button_Image] foreign key ([ImageId]) references [Framework].[ImageFile] ([Id]),
);