create table [Content].[CommentMedia] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [CommentId] uniqueidentifier not null,
    [Type] int default(0) not null,
    [AudioId] uniqueidentifier null,
    [ImageId] uniqueidentifier null,
    [PdfId] uniqueidentifier null,
    [VideoId] uniqueidentifier null,
    [Ordinal] int not null,
    constraint [PK_Content_CommentMedia] primary key clustered ([Id]),
    constraint [FK_Content_CommentMedia_Comment] foreign key ([CommentId]) references [Content].[Comment] ([Id]),
    constraint [FK_Content_CommentMedia_Audio] foreign key ([AudioId]) references [Framework].[AudioFile] ([Id]),
    constraint [FK_Content_CommentMedia_Image] foreign key ([ImageId]) references [Framework].[ImageFile] ([Id]),
    constraint [FK_Content_CommentMedia_Pdf] foreign key ([PdfId]) references [Framework].[PdfFile] ([Id]),
    constraint [FK_Content_CommentMedia_Video] foreign key ([VideoId]) references [Framework].[VideoFile] ([Id]),
);