create table [Content].[Container] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [DirectionId] uniqueidentifier not null,
    [WrapId] uniqueidentifier not null,
    [JustifyContentId] uniqueidentifier not null,
    [AlignItemsId] uniqueidentifier not null,
    [AlignContentId] uniqueidentifier not null,
    [Gap] nvarchar(10) null,
    constraint [PK_Content_Container] primary key clustered ([Id]),
    constraint [FK_Content_Container_Direction] foreign key ([DirectionId]) references [Content].[Direction] ([Id]),
    constraint [FK_Content_Container_Wrap] foreign key ([WrapId]) references [Content].[Wrap] ([Id]),
    constraint [FK_Content_Container_JustifyContent] foreign key ([JustifyContentId]) references [Content].[JustifyContent] ([Id]),
    constraint [FK_Content_Container_AlignItems] foreign key ([AlignItemsId]) references [Content].[AlignItems] ([Id]),
    constraint [FK_Content_Container_AlignContent] foreign key ([AlignContentId]) references [Content].[AlignContent] ([Id]),
);