create table [Content].[Course] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [TrackId] uniqueidentifier not null,
    [BinderId] uniqueidentifier not null,
    [Title] nvarchar(75) not null,
    [Description] nvarchar(max) not null,
    [StatusId] uniqueidentifier not null,
    [RequiresAchievementId] uniqueidentifier null,
    [GeneratesAchievementId] uniqueidentifier null,
    [Ordinal] int not null,
    constraint [PK_Content_Course] primary key clustered ([Id]),
    constraint [FK_Content_Course_Track] foreign key ([TrackId]) references [Content].[Track] ([Id]),
    constraint [FK_Content_Course_Binder] foreign key ([BinderId]) references [Content].[Binder] ([Id]),
    constraint [FK_Content_Course_Status] foreign key ([StatusId]) references [Framework].[ContentStatus] ([Id]),
    constraint [FK_Content_Course_RequiresAchievement] foreign key ([RequiresAchievementId]) references [Content].[Achievement] ([Id]),
    constraint [FK_Content_Course_GeneratesAchievement] foreign key ([GeneratesAchievementId]) references [Content].[Achievement] ([Id]),
);