create table [Content].[Email] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [MembershipId] uniqueidentifier not null,
    [FromName] nvarchar(150) not null,
    [FromEmail] nvarchar(75) not null,
    [TemplateId] uniqueidentifier null,
    [Send] datetimeoffset(7) not null,
    [Subject] nvarchar(150) not null,
    [Body] nvarchar(max) not null,
    [Status] int default(0) not null,
    [Processed] datetimeoffset(7) null,
    [BatchId] uniqueidentifier null,
    constraint [PK_Content_Email] primary key clustered ([Id]),
    constraint [FK_Content_Email_Membership] foreign key ([MembershipId]) references [Content].[Membership] ([Id]),
    constraint [FK_Content_Email_Template] foreign key ([TemplateId]) references [Content].[EmailTemplate] ([Id]),
);