create table [Content].[EmailTemplate] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [MembershipId] uniqueidentifier null,
    [Title] nvarchar(75) not null,
    [Subject] nvarchar(150) not null,
    [Body] nvarchar(max) not null,
    [PortalId] uniqueidentifier null,
    [OrganizationId] uniqueidentifier null,
    constraint [PK_Content_EmailTemplate] primary key clustered ([Id]),
    constraint [FK_Content_EmailTemplate_Membership] foreign key ([MembershipId]) references [Content].[Membership] ([Id]),
    constraint [FK_Content_EmailTemplate_Portal] foreign key ([PortalId]) references [Framework].[Portal] ([Id]),
    constraint [FK_Content_EmailTemplate_Organization] foreign key ([OrganizationId]) references [Framework].[Organization] ([Id]),
);