create table [Content].[Message] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [StageId] uniqueidentifier not null,
    [Name] nvarchar(75) null,
    [PopulationId] uniqueidentifier null,
    [MessageTypeId] uniqueidentifier null,
    [EmailTemplateId] uniqueidentifier null,
    [SmsTemplateId] uniqueidentifier null,
    [Ordinal] int null,
    [ActivationId] uniqueidentifier null,
    [DefinitionId] uniqueidentifier null,
    [MembershipId] uniqueidentifier null,
    [EmailId] uniqueidentifier null,
    [SmsId] uniqueidentifier null,
    [ActivationStageId] uniqueidentifier null,
    constraint [PK_Content_Message] primary key clustered ([Id]),
    constraint [FK_Content_Message_Stage] foreign key ([StageId]) references [Content].[Stage] ([Id]),
    constraint [FK_Content_Message_Population] foreign key ([PopulationId]) references [Content].[Population] ([Id]),
    constraint [FK_Content_Message_MessageType] foreign key ([MessageTypeId]) references [Content].[MessageType] ([Id]),
    constraint [FK_Content_Message_EmailTemplate] foreign key ([EmailTemplateId]) references [Content].[EmailTemplate] ([Id]),
    constraint [FK_Content_Message_SmsTemplate] foreign key ([SmsTemplateId]) references [Content].[SmsTemplate] ([Id]),
    constraint [FK_Content_Message_Activation] foreign key ([ActivationId]) references [Content].[Activation] ([Id]),
    constraint [FK_Content_Message_Definition] foreign key ([DefinitionId]) references [Content].[Message] ([Id]),
    constraint [FK_Content_Message_Membership] foreign key ([MembershipId]) references [Content].[Membership] ([Id]),
    constraint [FK_Content_Message_Email] foreign key ([EmailId]) references [Content].[Email] ([Id]),
    constraint [FK_Content_Message_Sms] foreign key ([SmsId]) references [Content].[Sms] ([Id]),
    constraint [FK_Content_Message_ActivationStage] foreign key ([ActivationStageId]) references [Content].[ActivationStage] ([Id]),
);