create table [Content].[MultimediaItem] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [MultimediaElementId] uniqueidentifier not null,
    [BoxId] uniqueidentifier null,
    [ItemId] uniqueidentifier null,
    [MediaTypeIndex] int not null,
    [AudioId] uniqueidentifier null,
    [ButtonId] uniqueidentifier null,
    [ImageId] uniqueidentifier null,
    [Text] nvarchar(max) null,
    [VideoId] uniqueidentifier null,
    [Ordinal] int not null,
    constraint [PK_Content_MultimediaItem] primary key clustered ([Id]),
    constraint [FK_Content_MultimediaItem_MultimediaElement] foreign key ([MultimediaElementId]) references [Content].[MultimediaElement] ([Id]),
    constraint [FK_Content_MultimediaItem_Audio] foreign key ([AudioId]) references [Framework].[AudioFile] ([Id]),
    constraint [FK_Content_MultimediaItem_Button] foreign key ([ButtonId]) references [Content].[Button] ([Id]),
    constraint [FK_Content_MultimediaItem_Image] foreign key ([ImageId]) references [Framework].[ImageFile] ([Id]),
    constraint [FK_Content_MultimediaItem_Video] foreign key ([VideoId]) references [Framework].[VideoFile] ([Id]),
);