create table [Content].[NoteElement] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [ElementId] uniqueidentifier not null,
    [Instructions] nvarchar(max) not null,
    [ImageFileId] uniqueidentifier null,
    [RequireText] bit default(0) not null,
    [RequireImageSelection] bit default(0) not null,
    constraint [PK_Content_NoteElement] primary key clustered ([Id]),
    constraint [FK_Content_NoteElement_Element] foreign key ([ElementId]) references [Content].[Element] ([Id]),
    constraint [FK_Content_NoteElement_ImageFile] foreign key ([ImageFileId]) references [Framework].[ImageFile] ([Id]),
);