create table [Content].[Page] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [BinderId] uniqueidentifier null,
    [TypeId] uniqueidentifier not null,
    [Title] nvarchar(150) not null,
    [BoxId] uniqueidentifier null,
    [StatusId] uniqueidentifier not null,
    [ShowNotebook] bit default(0) not null,
    [ShowGuide] bit default(0) not null,
    [GuideText] nvarchar(max) null,
    [GuideAudioId] uniqueidentifier null,
    [Ordinal] int not null,
    constraint [PK_Content_Page] primary key clustered ([Id]),
    constraint [FK_Content_Page_Binder] foreign key ([BinderId]) references [Content].[Binder] ([Id]),
    constraint [FK_Content_Page_Type] foreign key ([TypeId]) references [Content].[PageType] ([Id]),
    constraint [FK_Content_Page_Box] foreign key ([BoxId]) references [Content].[Box] ([Id]),
    constraint [FK_Content_Page_Status] foreign key ([StatusId]) references [Framework].[ContentStatus] ([Id]),
    constraint [FK_Content_Page_GuideAudio] foreign key ([GuideAudioId]) references [Framework].[AudioFile] ([Id]),
);