create table [Content].[Post] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [BlogId] uniqueidentifier not null,
    [PageId] uniqueidentifier not null,
    [StatusId] uniqueidentifier not null,
    [Title] nvarchar(150) not null,
    [Author] nvarchar(150) not null,
    [Published] date not null,
    [Revised] date null,
    [CommentRule] int default(0) not null,
    constraint [PK_Content_Post] primary key clustered ([Id]),
    constraint [FK_Content_Post_Blog] foreign key ([BlogId]) references [Content].[Blog] ([Id]),
    constraint [FK_Content_Post_Page] foreign key ([PageId]) references [Content].[Page] ([Id]),
    constraint [FK_Content_Post_Status] foreign key ([StatusId]) references [Framework].[ContentStatus] ([Id]),
);