create table [Content].[Publication] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [PortalId] uniqueidentifier not null,
    [GroupId] uniqueidentifier null,
    [StatusId] uniqueidentifier not null,
    [Title] nvarchar(300) not null,
    [Citation] nvarchar(max) null,
    [Venue] nvarchar(250) null,
    [Sample] nvarchar(500) null,
    [Timeline] nvarchar(100) null,
    [Outcome] nvarchar(1000) null,
    [Intervention] nvarchar(1000) null,
    [ImageId] uniqueidentifier null,
    [ImageAlt] nvarchar(300) null,
    [Year] int null,
    [Ordinal] int not null,
    constraint [PK_Content_Publication] primary key clustered ([Id]),
    constraint [FK_Content_Publication_Portal] foreign key ([PortalId]) references [Framework].[Portal] ([Id]),
    constraint [FK_Content_Publication_Group] foreign key ([GroupId]) references [Content].[PublicationGroup] ([Id]),
    constraint [FK_Content_Publication_Status] foreign key ([StatusId]) references [Framework].[ContentStatus] ([Id]),
    constraint [FK_Content_Publication_Image] foreign key ([ImageId]) references [Framework].[ImageFile] ([Id]),
);