create table [Content].[QuestionReply] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [SurveyReplyId] uniqueidentifier null,
    [QuestionId] uniqueidentifier not null,
    [Submitted] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [BoolValue] bit null,
    [TextValue] nvarchar(max) null,
    [HtmlValue] nvarchar(max) null,
    [DateValue] date null,
    [TimeValue] time null,
    [DateTimeValue] datetimeoffset(7) null,
    [IntegerValue] int null,
    [DecimalValue] real null,
    [CurrencyValue] real null,
    [OtherBoolValue] bit default(0) null,
    [OtherTextValue] nvarchar(150) null,
    [AudioId] uniqueidentifier null,
    [ImageId] uniqueidentifier null,
    [PdfId] uniqueidentifier null,
    [VideoId] uniqueidentifier null,
    [PostalId] uniqueidentifier null,
    constraint [PK_Content_QuestionReply] primary key clustered ([Id]),
    constraint [FK_Content_QuestionReply_SurveyReply] foreign key ([SurveyReplyId]) references [Content].[SurveyReply] ([Id]),
    constraint [FK_Content_QuestionReply_Question] foreign key ([QuestionId]) references [Content].[Question] ([Id]),
    constraint [FK_Content_QuestionReply_Audio] foreign key ([AudioId]) references [Framework].[AudioFile] ([Id]),
    constraint [FK_Content_QuestionReply_Image] foreign key ([ImageId]) references [Framework].[ImageFile] ([Id]),
    constraint [FK_Content_QuestionReply_Pdf] foreign key ([PdfId]) references [Framework].[PdfFile] ([Id]),
    constraint [FK_Content_QuestionReply_Video] foreign key ([VideoId]) references [Framework].[VideoFile] ([Id]),
    constraint [FK_Content_QuestionReply_Postal] foreign key ([PostalId]) references [Framework].[UsaPostal] ([Id]),
);