create table [Content].[SmsMessageMedia] (
    [Id] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [SmsMessageId] uniqueidentifier not null,
    [ImageId] uniqueidentifier null,
    [ProviderMediaId] nvarchar(75) null,
    [ProviderMediaUrl] nvarchar(500) null,
    [ContentType] nvarchar(100) null,
    [FileName] nvarchar(150) null,
    [SizeBytes] int null,
    [DownloadStatus] int default(0) not null,
    [Downloaded] datetimeoffset(7) null,
    [ErrorMessage] nvarchar(500) null,
    [Ordinal] int not null,
    constraint [PK_Content_SmsMessageMedia] primary key clustered ([Id]),
    constraint [FK_Content_SmsMessageMedia_SmsMessage] foreign key ([SmsMessageId]) references [Content].[SmsMessage] ([Id]),
    constraint [FK_Content_SmsMessageMedia_Image] foreign key ([ImageId]) references [Framework].[ImageFile] ([Id]),
);