create table [Content].[Track] (
    [Id] uniqueidentifier not null,
    [VersionOf] uniqueidentifier not null,
    [Updated] datetimeoffset(7) default(sysdatetimeoffset()) not null,
    [UpdatedBy] uniqueidentifier not null,
    [IsDeleted] bit default(0) not null,
    [PortalId] uniqueidentifier not null,
    [Title] nvarchar(75) not null,
    [Description] nvarchar(max) not null,
    [StatusId] uniqueidentifier not null,
    [RequiresAchievementId] uniqueidentifier null,
    [GeneratesAchievementId] uniqueidentifier null,
    [RequireSequentialCompletion] bit default(1) not null,
    [Ordinal] int not null,
    constraint [PK_Content_Track] primary key clustered ([Id]),
    constraint [FK_Content_Track_Portal] foreign key ([PortalId]) references [Framework].[Portal] ([Id]),
    constraint [FK_Content_Track_Status] foreign key ([StatusId]) references [Framework].[ContentStatus] ([Id]),
    constraint [FK_Content_Track_RequiresAchievement] foreign key ([RequiresAchievementId]) references [Content].[Achievement] ([Id]),
    constraint [FK_Content_Track_GeneratesAchievement] foreign key ([GeneratesAchievementId]) references [Content].[Achievement] ([Id]),
);